spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/attendance
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
